### derict
GET   http://localhost:8080/hello

### proxy
GET   http://localhost:9090/hello

### derict
POST http://localhost:8080/hello
Content-Type: application/json
{
    "name": "John"
}

### proxy
POST http://localhost:9090/hello
Content-Type: application/json
{
    "name": "John"
}
